### ISSUE TITLE
makefile

### ISSUE THREAD

**Issue by Andrew-Eathan** [100PXSquared/DerpiOS#1]
ew why are you not using a makefile
actually disgusting

**Comment by Derpius** [comment]
Why don’t you have a tracer more advanced than hard shadows and dot shading @Andrew-Eathan :trollface:

**Comment by Andrew-Eathan** [comment]
why are you mentioning that when it has nothing to do with the current topic
clearly you are mentally deranged :trollface:

**Comment by Derpius** [comment]
@Andrew-Eathan I’ll switch to a makefile when you write a path tracer (Lambertian diffuse and Cook-Torrance reflection only)

**Comment by Andrew-Eathan** [comment]
go touch some grass nerd :trollface:
